// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
public class SocketMessage
{
	private int len;
	private int sid;
	private int rid;
	private int isZip;
	private byte[] data;
	
	public SocketMessage(){
		this.clear();
	}

	public void clear(){
		data = new byte[1];
		len = 0;
		sid = 0;
		rid = 0;
		isZip = 0;
	}

	public int IsZip {
		get {
			return isZip;
		}
		set {
			isZip = value;
		}
	}

	public byte[] Data {
		get {
			return data;
		}
		set {
			data = value;
		}
	}

	public int Rid {
		get {
			return rid;
		}
		set {
			rid = value;
		}
	}
 

	public int Sid {
		get {
			return sid;
		}
		set {
			sid = value;
		}
	}



	public int Len {
		get {
			return len;
		}
		set {
			len = value;
			if(value>this.Data.Length){
				this.data = new byte[value+10];
			}
		}
	}
}


